### ISSUE TITLE
Resident set size instead of virtual memory size

### ISSUE THREAD

**Issue by nbenn** [shinra-dev/memuse#8]
When determining memory usage of the current process under linux, I personally find the fields `VmRSS` and `VmHWM` to be closer to what I'd intuitively expect to correspond to

> Sys.procmem() returns the total memory usage of the current R process and (if supported), the maximum memory usage as well.

From the [proc manpages](http://man7.org/linux/man-pages/man5/proc.5.html):

* `VmPeak`: Peak virtual memory size.
* `VmSize`: Virtual memory size.
* `VmHWM`: Peak resident set size ("high water mark").
* `VmRSS`: Resident set size. Note that the value here is the sum of RssAnon, RssFile, and RssShmem.

The reason why I'm reporting this is that when using memory mapped files and multiple processes, the values as reported by `Sys.procmem()` are massively inflated under linux compared to macOS.

Currently, under linux, mapping a 30 GB file into 8 processes, will yield 200 GB memory use, while staying in the 10's of GB on macOS. The 200 GB reported under linux have nothing to do with what I understand as memory usage but rather corresponds to the available/mapped "address space" (I'm a bit unsure on the precise terminology here).

After making the suggested change, the two platforms report much more similar memory usage.

I'm opening a PR in case you agree with my logic.

**Comment by wrathematics** [comment]
Ahh yeah, that makes sense. Thanks!
